### ISSUE TITLE
Supply Search Query in URL for Store Page

### ISSUE THREAD

**Issue by OfficialCRUGG** [PreMiD/Website#104]
In my opinion, you should be able to supply a Search Query in the URL, like this:
`https://premid.app/store?search=Test`
What would this be used for? Linking to a search for something obviously (e.g. linking to all Presences with "Google" in them) and even for [DDG Bangs](https://duckduckgo.com/bang).

**Comment by paz** [comment]
document.querySelector('.searchbar').value = new URLSearchParams(window.location.search).get('q')

**Comment by Voknehzyr** [comment]
Already planned that, thanks @paz for this code, would be really helpful.
