### ISSUE TITLE
Website | Presence Author Profile displays an empty page

### ISSUE THREAD

**Issue by DarkVillager** [PreMiD/Website#1077]
I try to load e.g. [https://premid.app/users/638080361179512853](https://premid.app/users/638080361179512853) from the url (so not form the homepage or store) and i just see the presences then it buffers and i get an empty screen
![image](https://github.com/PreMiD/Website/assets/42322979/542a194f-09cc-4b56-af46-ed0be1045d2f)

**Comment by Bas950** [comment]
Fixed in https://github.com/PreMiD/Website/pull/1082
