### ISSUE TITLE
Slow & not working downloads

### ISSUE THREAD

**Issue by ACertainCoder** [PreMiD/Website#108]
Currently, it's not possible to download the premid application in a normal amount of time. It's just downloading with 3 KB/s - 50 KB/s (tested the Windows x64 & x32 as well as macOS download). I tried to download it on my pc, mobile and in a completely other wifi network with another pc. It's everywhere the same.

Screenshot - PC1:
![j9VRlv49FF](https://user-images.githubusercontent.com/47316898/71693183-1816e580-2dac-11ea-9a02-f8397b6773df.png)

Screenshot - PC2:
![unknown](https://user-images.githubusercontent.com/47316898/71693831-beafb600-2dad-11ea-86fa-634b5d9e5293.png)

The problem is not only that it takes a long time. After a while, the server appears to no longer provide the download. Firefox 71.0 (64bit) reports after half an hour to a full hour that the download couldn't continue. Even if I press the button to reconnect and continue the download it's not downloading anymore.

**Comment by frozaum** [comment]
i'm disappointed with u @github

**Comment by ACertainCoder** [comment]
The download seems to be working properly again.
