### ISSUE TITLE
Website simply wont show up properly in chrome browser (Fresh W11 System)

### ISSUE THREAD

**Issue by Myrothas** [PreMiD/Website#1089]
store page  can be seen for a second and then it disappears
windows 11 recent version
google chrome browser
![premid website](https://github.com/PreMiD/Website/assets/87095612/0f2fbf49-251c-4d32-bbf0-378f3bdd6555)

**Comment by alexbcberio** [comment]
Hello @Myrothas,

I see you have multiple extensions on the browser, it might be caused by them.
The website asks consent to use cookies and it flickers, try disabling any ad-blocking/privacy extensions and reload the page. Set-up the cookie consent popup and try enabling again those extensions.

**Comment by Myrothas** [comment]
Youre correct, it was the extension uBlock origin.
Thanks!
