### ISSUE TITLE
Website Development Plan for February 2020

### ISSUE THREAD

**Issue by Voknehzyr** [PreMiD/Website#132]
This plan shows the features that should be done until **February** ends.
You are free to suggest your features by referring to this Issue.

Tasks that are marked with ⏰ have the first-order priority.

#### Userpage
- [ ] ⏰ Move the presences to the store and display only author's created ones. (Fixes #72)
- [ ] Add more elements for better navigation.
- [x] Optimize SEO.

#### Store
- [ ] Find a better solution for presence thumbnails.
- [ ] Apply a better design to the pagination.

#### Global
- [ ] ⏰ Migrate website CSS to a better class system.
- [ ] ⏰ Add new CSS elements for fast page development.

#### Userpage
- [ ] Optimize data fetching and processing.

#### Store
- [x] ⏰ Advanced search that includes search by tags, author, and etc. (Fixes #104)
- [ ] Better display of the RegExp on presence page.
- [x] ⏰ Fix problems with URL parsing on presence page.
- [ ] ⏰ Add URL display limit to make better UX.
- [ ] Find a better way to detect PreMiD extension.
- [ ] Optimize data fetching and processing.
- [x] The contributors tag over the presence metadata file.
- [ ] Hide owned presences checkbox.

#### Global
- [ ] Optimize Vuex store, plugins, and modules.

## API 

- [ ] Date added for presences endpoint.
- [ ] Likes endpoint.
- [x] Better way to fetch userdata to prevent empty presence authors.

**Comment by frozaum** [comment]
The contributors tag over the presence metadata file is been a thing for quite a while ago, and yet, it's not visible over the presence page, which it should be.

**Comment by Voknehzyr** [comment]
> The contributors tag over the presence metadata file is a thing for quite a while, and yet, it's not visible over the presence page, which it should be.

Added.

**Comment by frozaum** [comment]
another idea that i originally gave over the #general channel
![image](https://user-images.githubusercontent.com/34042085/73588440-eaef4d00-44a7-11ea-989f-dd4d3213aee7.png)

**Comment by frozaum** [comment]
#136

**Comment by frozaum** [comment]
@Voknehzyr Don't forget about some ideas that people has made over this.
https://twitter.com/PreMiDapp/status/1185654220961259522

**Comment by frozaum** [comment]
![image](https://user-images.githubusercontent.com/34042085/73706002-15265200-46d6-11ea-9f59-dbe7992fa225.png)

**Comment by frozaum** [comment]
the partners page
