### ISSUE TITLE
Add all button

### ISSUE THREAD

**Issue by xamionex** [PreMiD/Website#136]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when i need to add all my presences if i reinstall or update

**Describe the solution you'd like**
A button that simply adds all the presences in the presence store

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by Voknehzyr** [comment]
Sorry, we can't make that function.
Having that type of option will create a high overload for your PC & our servers.
Soon*tm* we will add syncing between extension and your account to keep presences saved.
