### ISSUE TITLE
Keep Talking and Nobody Explodes missing in the store & profile issues

### ISSUE THREAD

**Issue by ACertainCoder** [PreMiD/Website#161]
I've added KTANE like 2 - 3 days ago and it got merged into the Presence repo of PreMiD. The funny thing is that it's now showing up in the store (neither default or beta):
![grafik](https://user-images.githubusercontent.com/47316898/75199331-2279ae00-5763-11ea-8683-c9cbf1625a76.png)

Up on top, I had to message a moderator to get the Presence Developer role - which maybe was caused by this missing Presence and my also be the reason why my profile doesn't load too:
![grafik](https://user-images.githubusercontent.com/47316898/75199477-800dfa80-5763-11ea-8880-01ded6fa64fe.png)

**Comment by Timeraa** [comment]
It's on our website tho??? https://premid.app/store/presences/Keep%20Talking%20and%20Nobody%20Explodes

**Comment by ACertainCoder** [comment]
🤷‍♂ A few days ago it wasn't. But thanks for the hint tho.
