### ISSUE TITLE
"Please disable your adblock.", well it is.

### ISSUE THREAD

**Issue by destr0yed** [PreMiD/Website#237]
![yup](https://user-images.githubusercontent.com/20506021/79057055-2606bd00-7c5d-11ea-9fe2-e68429395f26.png)

**Comment by OfficialCRUGG** [comment]
Are you using a VPN or some other extension that blocks some ads (like the DuckDuckGo Extension for example)?
Otherwise, try using a different Browser like Chrome (or just Firefox Nightly but I'm not sure if that syncs with normal Firefox) without Extensions and see if it works there.

**Comment by destr0yed** [comment]
> Are you using a VPN or some other extension that blocks some ads (like the DuckDuckGo Extension for example)?

No, I am only using uBlock Origin which is disabled on all sites on 'premid.app'.
I also turned off the 'Enhanced Tracking Protection' function.

> Otherwise, try using a different Browser like Chrome (or just Firefox Nightly but I'm not sure if that syncs with normal Firefox) without Extensions and see if it works there.

It does not make sense to me why I should install a completely different application just to download an app. From now on I will use Edge to get around this barrier. I do not know which extension tries to block my disabled adblocker but the people who programmed/pasted it for use on their website should think about testing it with all browsers before pushing. It is not only this site trying to block an disabled adblock; for example many news sites using it too, making them unable to read anything on there.

For anyone else who gets this: Just use Edge to download, luckily an auto-updater is included in PreMiD.

**Comment by OfficialCRUGG** [comment]
I just got a Clean Install of Firefox and Added uBlock Origin and it didn't even detect the AdBlocker...
It has to be an Issue on your Site. Also do you really think the Dev Team is able to test the website with every single Browser with every single out of the Ad Blocking Extensions? This is Open-Source & Free Software. Be happy that you get this for free.

**Comment by llacb47** [comment]
Update your filters in uBo, it's been fixed.
