### ISSUE TITLE
Contributors page - copy Id

### ISSUE THREAD

**Issue by Eviu** [PreMiD/Website#391]
When i click to copy user's id in Contributors page i got "undefined" written on my clipboard.
i'm currently using **Chrome 84** on Linux.

I didn't have tested in other browsers. (Sorry for that)

**Comment by kawakaami** [comment]
Yep, same thing for me. (Linux - Firefox 78.0.2)

**Comment by flarely** [comment]
Same thing for me! (MacOS - Edge 85.0.564.41)

**Comment by Alanexei** [comment]
Resolved
