### ISSUE TITLE
Various store upgrades

### ISSUE THREAD

**Issue by paz** [PreMiD/Website#51]
- [ ] featured section at the top
- [x] actual sortable tags other than just nsfw
- [x] a tag for large sites so it isnt cluttered by a million pirate anime sites
- [x] PAGINATION??? maybe/??

**Comment by OfficialCRUGG** [comment]
Agree with all of them ;)
(But there aren't that many pirate anime sites... Only two to be exact.

**Comment by paz** [comment]
u get the idea tho.. like netflix/youtube/twitch would have the "large site" tag
