### ISSUE TITLE
Suggestion to not hide added presences

### ISSUE THREAD

**Issue by Cairo2k18** [PreMiD/Website#534]
Not hiding them somewhat makes more sense as it is meant to show "All" presences (possibly there could be something done to more clearly differentiate added ones to non-added ones).

But right now, it seems a bit clunky and leaves a much greater room for mis clicks, etc.

**Comment by EncryptedDev** [comment]
This filter though - "Show added presences"
![image](https://user-images.githubusercontent.com/64903135/113912541-28014e80-97d3-11eb-9c1d-472a4009b8f8.png)

**Comment by Bas950** [comment]
> This filter though - "Show added presences"
> ![image](https://user-images.githubusercontent.com/64903135/113912541-28014e80-97d3-11eb-9c1d-472a4009b8f8.png)
