### ISSUE TITLE
[request] Hide discord tags (discriminators) on the homepage

### ISSUE THREAD

**Issue by Migushthe2nd** [PreMiD/Website#544]
From what I understand, every PreMiD user has a chance to be displayed on the homepage. This might be an issue for some people. I had never given this any thought, until some random person DMed me about my profile pricture he saw on the main page. I'm not too keen on receiving useless messages from completely unknown people. Now imagine if a well known person was to show up on the homepage, and it turns out to be their real account. It would require them to either change their Discord username, pay for Nitro and change their discriminator (which won't even ensure that it won't happen again), or block direct messages and friend requests.

**Comment by Bas950** [comment]
@Timeraa is already making a command for this to hide yourself from the contributors page, this should also hide you from the homepage.

**Comment by Timeraa** [comment]
I made a command for it but it seems to be broken, I am going to check if it works later and if not fix it and respond to you.

**Comment by Migushthe2nd** [comment]
I think it might be best to simply hide the discriminators on the homepage by default (usernames seem fine). It being an opt-out is less user-friendly, since it requires users to do research on how to hide themselves, join a specific Discord server and run a command, _just_ to disable something they didn't even ask for. If it hurts the homepage's look, you could consider showing random discriminators. Someone who's on the contributers page is more likely to already be in the the PreMiD Discord server, for _them_ it wouldn't be much of a hassle to run a command.

**Comment by ririxidev** [comment]
No no no, look. If you are on our discord server, you can be displayed. We display people from our discord server only. You can always leave your discord 🤔

**Comment by Migushthe2nd** [comment]
Ah okay, thanks for the explanation.

**Comment by QkeleQ10** [comment]
`/preferences showDiscrimOnSite` and `/preferences showOnSite`?

**Comment by Bas950** [comment]
`/preferences showcontributor:False`
