### ISSUE TITLE
Issue after refreshing

### ISSUE THREAD

**Issue by marinofranz** [PreMiD/Website#593]
Things glitch out after refreshing for some reason.
I am using the browser Opera GX.

Refer to video:
https://user-images.githubusercontent.com/48334228/109318292-8edf2f80-7845-11eb-95f7-c8254b49e0f1.mp4

**Comment by TheDropX** [comment]
Hey there,

Sorry for the late response, we didn't check the issues for a pretty long while now.

Unfortunately, I am not able to reproduce the bug that you've been encountering. I tried reproducing it on my fresh installed Opera GX browser, but it was working as it should. I wonder if it was an issue with the browser at that period of time and maybe it got fixed, so could you please try to check if you are still getting the glitch?

I would like to apologize again for the slow response.

Alex,
PreMiD Management

**Comment by marinofranz** [comment]
Hi,

I'm pretty sure this got fixed, so I'm just going to close this issue. Apologies for not letting you know that it had been fixed.

Thanks,
Marino
