### ISSUE TITLE
Logo is displayed incorrectly on iOS

### ISSUE THREAD

**Issue by VocalZero** [PreMiD/Website#607]
## Hello 👋

Your website is displayed incorrectly on my phone or in other words the logo is very stretched there. I tried it on an iPhone Xs with Safari and Chrome. Both have the same problem.

## Screenshots
![SPRK_default_preset_name_custom – 1](https://user-images.githubusercontent.com/20924469/111389221-df151900-86b0-11eb-8923-9e983d79e238.png)

**Comment by EncryptedDev** [comment]
I do believe this issue was fixed a while back as I cannot reproduce it at the time of writing this.

**Comment by VocalZero** [comment]
Problem seems to have been fixed. I will close my issue
