### ISSUE TITLE
Presence Store not properly displaying extensions which end with `.js`

### ISSUE THREAD

**Issue by fuwn** [PreMiD/Website#617]
Navigating to [Discord.js](https://premid.app/store/presences/Discord.js)'s presence page notifies you with `/* script not found */`.

**Comment by TheDropX** [comment]
Hey there, 

Sorry for the late response and fix, we didn't check the issues for a pretty long while now.
I could view the discord.js presence page in the development enviroment, it worked as normal, but it looked like it wasn't on production. But after a small change in the website's configuration, it works. 

I would like to apologize again for the slow fix.

Alex,
PreMiD Management
