### ISSUE TITLE
Contributors doesn't display roles correctly

### ISSUE THREAD

**Issue by Jackelele** [PreMiD/Website#964]
The formatting of how the roles are displayed under "Staff" seems to be broken. 

Shows "contributors.roles.discordModerator" etc. 

![iJW1eC](https://user-images.githubusercontent.com/20693601/176898028-65515347-2d65-4e4b-b64c-5ddf3631c04a.png)

Tested on Brave (Version 1.40.109  Chromium: 103.0.5060.66 (Official Build) and Google Chrome (same version).

**Comment by EncryptedDev** [comment]
Resolved in PreMiD/Website#981 and PreMiD/Localization#7198
